// <auto-generated />
namespace Client.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SpareParts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpareParts));
        
        string IMigrationMetadata.Id
        {
            get { return "202506071045109_SpareParts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
